language: python
python:
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
# command to run tests, e.g. python setup.py test <package>
script: 
  - coverage run --rcfile=.coverage.rc src/manage.py test alltests
  - coverage report -m
after_success: coveralls --rcfile=.coverage.rc

fast_finish: true